---
- name: Check for available Linux updates
  tags:
    - linux_update
  block:
    - name: Update package manager cache (apt)
      ansible.builtin.apt:
        update_cache: true
      when: ansible_pkg_mgr == "apt"

    - name: Update package manager cache (dnf)
      ansible.builtin.dnf:
        refresh: true
      when: ansible_pkg_mgr == "dnf"

    - name: Update package manager cache (yum)
      ansible.builtin.yum: # noqa fqcn[action-core]
        name: "*"
        state: latest # noqa package-latest
        update_cache: true
      when: ansible_pkg_mgr == "yum"

    - name: Update package manager cache (apk)
      community.general.apk:
        update_cache: true
      when: ansible_pkg_mgr == "apk"

    - name: Check for available updates
      ansible.builtin.package_facts:
        manager: auto
      register: package_facts

- name: Install Linux updates if available
  tags:
    - linux_update
  block:
    - name: Install updates using package manager (apt)
      ansible.builtin.package:
        name: "*"
        state: latest # noqa package-latest
        update_cache: true
      when: package_facts.ansible_facts.package_mgr == "apt"

    - name: Install updates using apt
      ansible.builtin.apt:
        upgrade: safe
        autoremove: true
        autoclean: true
      when: package_facts.ansible_facts.package_mgr == "apt"

    - name: Install updates using package manager (dnf)
      ansible.builtin.package:
        name: "*"
        state: latest # noqa package-latest
        update_cache: true
      when: package_facts.ansible_facts.package_mgr == "dnf"

    - name: Install updates using dnf
      ansible.builtin.dnf:
        name: "*"
        state: latest # noqa package-latest
        update_cache: true
      when: package_facts.ansible_facts.package_mgr == "dnf"

    - name: Install updates using package manager (yum)
      ansible.builtin.package:
        name: "*"
        state: latest # noqa package-latest
        update_cache: true
      when: package_facts.ansible_facts.package_mgr == "yum"

    - name: Install updates using yum
      ansible.builtin.yum:  # noqa fqcn[action-core]
        name: "*"
        state: latest # noqa package-latest
        update_cache: true
      when: package_facts.ansible_facts.package_mgr == "yum"

    - name: Install updates using package manager (apk)
      ansible.builtin.package:
        name: "*"
        state: latest # noqa package-latest
        update_cache: true
      when: package_facts.ansible_facts.package_mgr == "apk"

    - name: Install updates using apk
      community.general.apk:
        name: "*"
        state: latest # noqa package-latest
        update_cache: true
      when: package_facts.ansible_facts.package_mgr == "apk"
