---
- name: Run Linux update playbook
  when: ansible_facts['ansible_distribution'] == 'Linux'
  block:
    - name: Linux update
      ansible.builtin.import_tasks: linux_update.yaml

- name: Run Windows update playbook
  when: ansible_facts['ansible_distribution'] == 'Windows'
  block:
    - name: Windows update
      ansible.builtin.import_tasks: windows_update.yaml
